function money(n){return new Intl.NumberFormat('fr-FR').format(Number(n)||0)+' DA'}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function cart(){return JSON.parse(localStorage.getItem('aura_cart')||'[]')}
function save(c){localStorage.setItem('aura_cart',JSON.stringify(c));updateCount()}
function updateCount(){let n=cart().reduce((a,x)=>a+x.q,0);document.querySelectorAll('.count').forEach(e=>e.textContent=n)}
function header(){document.getElementById('header').innerHTML=`<div class="top"><span>Livraison partout en Algérie</span><span>Paiement à la livraison · 0667 32 69 78</span></div><header><a class="logo" href="index.html">AURA-HIJAB<small>COLLECTION</small></a><nav><a href="index.html">Accueil</a><a href="boutique.html">Boutique</a><a href="a-propos.html">À propos</a><a href="contact.html">Contact</a></nav><a class="cart" href="panier.html">🛒<i class="count">0</i></a></header>`;updateCount()}
function footer(){document.getElementById('footer').innerHTML=`<footer><h2>AURA-HIJAB</h2><p>Hijabs élégants · catalogue personnalisable · Algérie</p><p>WhatsApp : 0667 32 69 78</p><small>© 2026 AURA-HIJAB</small></footer><a class="wa" href="https://wa.me/213667326978" target="_blank">☎</a>`}
function card(p){return `<article class="card"><a href="produit.html?id=${p.id}"><div class="photo"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"><b class="price-badge">${money(p.price)}</b></div></a><div class="info"><h3>${esc(p.name)}</h3><p>${esc(p.category)}</p><span class="price">${money(p.price)}</span><button class="buy" onclick="add(${p.id})">Ajouter</button></div></article>`}
function add(id){let c=cart(),x=c.find(a=>a.id==id);if(x)x.q++;else c.push({id:Number(id),q:1});save(c);alert('Produit ajouté au panier.')}
function home(){let e=document.getElementById('featured');if(e)e.innerHTML=PRODUCTS.slice(0,4).map(card).join('');let hero=document.getElementById('heroImage');if(hero&&PRODUCTS[0])hero.src=PRODUCTS[0].image}
function shop(){let e=document.getElementById('products'),cat='Tous';function draw(){e.innerHTML=PRODUCTS.filter(p=>cat==='Tous'||p.category===cat).map(card).join('')}document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat;draw()});draw()}
function product(){let id=+new URLSearchParams(location.search).get('id'),p=PRODUCTS.find(x=>x.id===id),e=document.getElementById('detail');if(!p){e.innerHTML='<div class="empty">Produit introuvable</div>';return}e.innerHTML=`<div class="detail-img"><img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div><div class="eyebrow">${esc(p.category)}</div><h1>${esc(p.name)}</h1><div class="bigprice">${money(p.price)}</div><p>${esc(p.description)}</p><p>Stock : ${Number(p.stock)||0}</p><button class="btn" onclick="add(${p.id})">Ajouter au panier</button></div>`}
function basket(){let e=document.getElementById('basket'),s=document.getElementById('summary'),c=cart();if(!c.length){e.innerHTML='<div class="empty">Votre panier est vide.<br><a class="btn" href="boutique.html">Voir la boutique</a></div>';s.innerHTML='';return}let sub=0;e.innerHTML=c.map(x=>{let p=PRODUCTS.find(a=>a.id==x.id);if(!p)return '';sub+=p.price*x.q;return `<div class="row"><span>${esc(p.name)} × ${x.q}</span><b>${money(p.price*x.q)}</b></div>`}).join('');let d=sub>=CONFIG.free?0:CONFIG.delivery;s.innerHTML=`<h2>Résumé</h2><div class="row"><span>Sous-total</span><b>${money(sub)}</b></div><div class="row"><span>Livraison</span><b>${d?money(d):'Gratuite'}</b></div><div class="row"><b>Total</b><b>${money(sub+d)}</b></div><a class="btn" href="commande.html">Commander</a>`}
function admin(){let t=document.getElementById('adminTable');if(!t)return;t.innerHTML=PRODUCTS.map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${p.stock}</td></tr>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{header();footer();home();if(document.getElementById('products'))shop();if(document.getElementById('detail'))product();if(document.getElementById('basket'))basket();admin()})
